# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpoll',
            name='yesno',
            field=models.BooleanField(default=False),
        ),
    ]
