# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentpoll_yesno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentpoll',
            name='yesno',
        ),
        migrations.RemoveField(
            model_name='assignmentpoll',
            name='yesnoabstain',
        ),
        migrations.AddField(
            model_name='assignmentpoll',
            name='pollmethod',
            field=models.CharField(default='yna', max_length=5),
        ),
    ]
