# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-03 13:23
from __future__ import unicode_literals

from django.db import migrations

from openslides.utils.models import MinMaxIntegerField


class Migration(migrations.Migration):

    dependencies = [("assignments", "0003_candidate_weight")]

    operations = [
        migrations.AddField(
            model_name="assignmentpoll",
            name="votesabstain",
            field=MinMaxIntegerField(null=True, blank=True, min_value=-2),
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="votesno",
            field=MinMaxIntegerField(null=True, blank=True, min_value=-2),
        ),
    ]
