# Generated by Django 2.1.5 on 2019-01-19 13:25

from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [("assignments", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="assignmentoption",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentrelateduser",
            name="user",
            field=models.ForeignKey(
                on_delete=openslides.utils.models.CASCADE_AND_AUTOUODATE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
