# Generated by Django 2.1.7 on 2019-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0003_auto_20190119_1425"),
        ("assignments", "0006_auto_20190119_1425"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="mediafiles.Mediafile"),
        )
    ]
