# Generated by Django 2.2.6 on 2019-10-17 08:40

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_postgresql_auth_group_id_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0007_assignment_attachments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignmentoption", old_name="candidate", new_name="user"
        ),
        migrations.RemoveField(model_name="assignmentpoll", name="description"),
        migrations.RemoveField(model_name="assignmentpoll", name="published"),
        migrations.AddField(
            model_name="assignmentpoll",
            name="global_abstain",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="global_no",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="groups",
            field=models.ManyToManyField(blank=True, to="users.Group"),
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "Created"),
                    (2, "Started"),
                    (3, "Finished"),
                    (4, "Published"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="title",
            field=models.CharField(default="Poll", max_length=255, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="type",
            field=models.CharField(
                choices=[
                    ("analog", "Analog"),
                    ("named", "Named"),
                    ("pseudoanonymous", "Pseudoanonymous"),
                ],
                default="analog",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="votes_amount",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="assignmentvote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="voted",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="allow_multiple_votes_per_candidate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignmentpoll",
            name="pollmethod",
            field=models.CharField(
                choices=[("YN", "YN"), ("YNA", "YNA"), ("votes", "votes")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="assignmentvote",
            name="value",
            field=models.CharField(
                choices=[("Y", "Y"), ("N", "N"), ("A", "A")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="assignmentvote",
            name="weight",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("-2"))],
            ),
        ),
        migrations.RenameField(
            model_name="assignmentpoll", old_name="votescast", new_name="db_votescast"
        ),
        migrations.RenameField(
            model_name="assignmentpoll",
            old_name="votesinvalid",
            new_name="db_votesinvalid",
        ),
        migrations.RenameField(
            model_name="assignmentpoll", old_name="votesvalid", new_name="db_votesvalid"
        ),
        migrations.RemoveField(model_name="assignmentpoll", name="votesabstain"),
        migrations.RemoveField(model_name="assignmentpoll", name="votesno"),
    ]
