# Generated by Django 1.9.9 on 2016-08-15 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'default_permissions': ()},
        ),
    ]
