# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160815_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='projector',
            name='speakeroverlay',
            field=models.BooleanField(default=False),
        ),
    ]
