# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160815_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='projector',
            name='height',
            field=models.PositiveIntegerField(default=768),
        ),
        migrations.AddField(
            model_name='projector',
            name='width',
            field=models.PositiveIntegerField(default=1024),
        ),
    ]
