# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:09
from __future__ import unicode_literals

import uuid

from django.db import migrations, models
from openslides.core.models import Projector


def add_speaker_overlay(apps, schema_editor):
    """
    Adds a list of speaker overlay to the existing projector id=1
    """
    # We disconnect the inform_changed_data_receiver to disabled the
    # autoupdate mechanism during migrations.
    models.signals.post_save.disconnect(
        dispatch_uid='inform_changed_data_receiver')

    # We get the model from the versioned app registry;
    # if we directly import it, it will be the wrong version.
    projector = Projector.objects.get(id=1)
    soverlay_uuid = uuid.uuid4().hex
    projector.config[soverlay_uuid] = {
        'name': 'core/speakeroverlay',
        'stable': True}
    projector.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projector_resolution'),
    ]

    operations = [
        migrations.RunPython(add_speaker_overlay)
    ]
