# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:26
from __future__ import unicode_literals

import uuid

from django.db import migrations, models
from openslides.core.models import Projector
from openslides.utils.autoupdate import inform_changed_data_receiver


def add_speaker_overlay(apps, schema_editor):
    """
    Adds a list of speaker overlay to the existing projector id=1
    """
    # We disconnect the inform_changed_data_receiver to disabled the
    # autoupdate mechanism during migrations.
    models.signals.post_save.disconnect(
        dispatch_uid='inform_changed_data_receiver')

    # We get the model from the versioned app registry;
    # if we directly import it, it will be the wrong version.
    projector = Projector.objects.get(id=1)
    soverlay_uuid = uuid.uuid4().hex
    projector.config[soverlay_uuid] = {
        'name': 'core/speakeroverlay',
        'stable': True}
    projector.save()

    # Reconnect autoupdate.
    models.signals.post_save.connect(
        inform_changed_data_receiver,
        dispatch_uid='inform_changed_data_receiver')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160918_2104'),
    ]

    operations = [
        migrations.RunPython(add_speaker_overlay)
    ]
