# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_auto_20170412_1258")]

    operations = [
        migrations.AlterField(
            model_name="projector",
            name="height",
            field=models.PositiveIntegerField(default=768),
        ),
        migrations.AlterField(
            model_name="projector",
            name="width",
            field=models.PositiveIntegerField(default=1024),
        ),
    ]
