# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_multiprojector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'default_permissions': (), 'permissions': (('can_use_chat', 'Can use the chat'), ('can_manage_chat', 'Can manage the chat'))},
        ),
    ]
