# Generated by Django 2.1.5 on 2019-01-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0010_auto_20190118_1908")]

    operations = [
        migrations.AlterField(
            model_name="history", name="now", field=models.DateTimeField()
        )
    ]
