# Generated by Django 2.1.5 on 2019-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0017_auto_20190219_2015")]

    operations = [
        migrations.AddField(
            model_name="projector",
            name="background_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="projector",
            name="header_background_color",
            field=models.CharField(default="#317796", max_length=7),
        ),
        migrations.AddField(
            model_name="projector",
            name="header_font_color",
            field=models.CharField(default="#f5f5f5", max_length=7),
        ),
        migrations.AddField(
            model_name="projector",
            name="header_h1_color",
            field=models.CharField(default="#317796", max_length=7),
        ),
        migrations.AddField(
            model_name="projector",
            name="show_header_footer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="projector",
            name="show_logo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="projector",
            name="show_title",
            field=models.BooleanField(default=True),
        ),
    ]
