# Generated by Django 2.1.5 on 2019-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0019_countdown_title_1")]

    operations = [
        migrations.AddField(
            model_name="countdown",
            name="title",
            field=models.CharField(max_length=256, unique=True),
        )
    ]
