# Generated by Django 2.1.7 on 2019-03-29 06:45

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def remove_chatmessage_permissions(apps, schema_editor):
    content_type = ContentType.objects.filter(model="chatmessage", app_label="core")
    Permission.objects.filter(content_type__in=content_type).delete()


class Migration(migrations.Migration):

    dependencies = [("core", "0021_auto_20190415_0942")]

    operations = [
        migrations.RunPython(remove_chatmessage_permissions),
        migrations.RemoveField(model_name="chatmessage", name="user"),
        migrations.DeleteModel(name="ChatMessage"),
    ]
