# Generated by Django 2.2 on 2019-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0022_remove_chatmessage")]

    operations = [
        migrations.AddField(
            model_name="projector",
            name="chyron_background_color",
            field=models.CharField(default="#317796", max_length=7),
        ),
        migrations.AddField(
            model_name="projector",
            name="chyron_font_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
