# Generated by Django 2.2.3 on 2019-07-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0024_auto_20190605_1105")]

    operations = [
        migrations.AddField(
            model_name="projector",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        )
    ]
