# Generated by Django 2.2.6 on 2019-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_projector_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="projector",
            name="aspect_ratio_numerator",
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name="projector",
            name="aspect_ratio_denominator",
            field=models.PositiveIntegerField(default=9),
        ),
    ]
