# Generated by Django 2.2.4 on 2019-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0026_history_migrations_1")]

    operations = [
        # No default here, because it is ensured in the last migration, that there are no HistoryData elements.
        migrations.AddField(
            model_name="historydata",
            name="migration_id",
            field=models.PositiveIntegerField(),
        ),
    ]
