# Generated by Django 2.2.12 on 2020-06-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_monospace_font"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projector",
            options={
                "default_permissions": (),
                "permissions": (
                    ("can_see_projector", "Can see the projector"),
                    ("can_manage_projector", "Can manage the projector"),
                    ("can_see_frontpage", "Can see the front page"),
                    ("can_see_livestream", "Can see the live stream"),
                ),
            },
        ),
    ]
