# Generated by Django 2.2 on 2019-06-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("agenda", "0007_list_of_speakers_3")]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "default_permissions": (),
                "ordering": ["weight"],
                "permissions": (
                    ("can_see", "Can see agenda"),
                    ("can_manage", "Can manage agenda"),
                    (
                        "can_see_internal_items",
                        "Can see internal items and time scheduling of agenda",
                    ),
                ),
            },
        )
    ]
