# Generated by Django 2.2.16 on 2020-10-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0009_item_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="point_of_order",
            field=models.BooleanField(default=False),
        ),
    ]
