# Generated by Django 2.2.19 on 2021-03-08 14:40

from django.db import migrations, models

import openslides.agenda.models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_speaker_point_of_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listofspeakers",
            name="closed",
            field=models.BooleanField(
                default=openslides.agenda.models.list_of_speakers_initially_closed
            ),
        ),
    ]
