# Generated by Finn Stutzenstein on 2021-03-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Reverts the previous migration to replace
    openslides.agenda.models.list_of_speakers_initially_closed
    with False. If this is a new database and the previous migration was
    not run before, this one has no effect.
    """

    dependencies = [
        ("agenda", "0011_list_of_speakers_closed_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listofspeakers",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
