name: 'Build service'
description: 'Builds service image for given context'
inputs:
  service:
    description: 'Name of the service. Examples: proxy, auth, datastore'
    required: true
  context:
    description: 'Build Context. Possible options: prod, dev, tests'
    required: true
  module:
    description: 'Optional module of the service. Examples: reader, writer'
    required: false
    default: ""
  port:
    description: 'Optional port of the service'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
      - name: "Build Service"
        shell: bash
        run: bash $GITHUB_ACTION_PATH/action-run.sh
        env:
          SERVICE: ${{ inputs.service }}
          CONTEXT: ${{ inputs.context }}
          MODULE: ${{ inputs.module }}
          PORT: ${{ inputs.port }}
          GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH