# Generated by Django 1.10.5 on 2017-01-11 21:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import openslides.users.models
import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0002_user_misc_default_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[(
                'group_ptr',
                models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='auth.Group'))],
            options={
                'default_permissions': (),
            },
            bases=(openslides.utils.models.RESTModelMixin, 'auth.group'),
            managers=[
                ('objects', openslides.users.models.GroupManager()),
            ],
        ),
    ]
