# Generated by Django 2.1.1 on 2018-09-07 21:01

from django.db import migrations


def delete_all_groups(apps, schema_editor):
    """
    Removes all groups so they are generated via signal again.
    """
    # We get the model from the versioned app registry;
    # if we directly import it, it will be the wrong version.
    Group = apps.get_model('users', 'Group')
    Group.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email'),
    ]

    operations = [
        migrations.RunPython(
            delete_all_groups,
        ),
    ]
