# Generated by Django 2.1.3 on 2018-12-06 07:58

from django.db import migrations, models
import openslides.utils.models


def move_groups_and_permissions_to_OpenSlides(apps, schema_editor):
    Group = apps.get_model('users', 'Group')
    NewGroup = apps.get_model('users', 'NewGroup')
    Permissions = apps.get_model('auth', 'Permission')
    User = apps.get_model('users', 'User')

    for old_group in Group.objects.all():
        permissions = []
        for perm in old_group.permissions.all():
            permissions.append('.'.join((perm.content_type.app_label, perm.codename,)))
        new_group = NewGroup(pk=old_group.pk, name=old_group.name)
        new_group.db_permissions = ','.join(permissions)
        new_group.save(skip_autoupdate=True)

    for user in User.objects.all():
        user.newGroups.set(user.groups.values_list('pk', flat=True))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('db_permissions', models.TextField()),
            ],
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='newGroups',
            field=models.ManyToManyField(to='users.NewGroup'),
        ),
        migrations.RunPython(move_groups_and_permissions_to_OpenSlides),
    ]
