# Generated by Django 2.1.5 on 2019-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0007_superadmin")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
