# Generated by Django 2.1.3 on 2018-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_drop_django_groups'),
        ('motions', '0017_comment_section_group_reference'),
    ]

    atomic = False

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='newGroups',
            new_name='groups',
        ),
        migrations.RenameModel(
            old_name='NewGroup',
            new_name='Group',
        ),
    ]
