# Generated by Django 2.1.5 on 2019-01-19 13:47

from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [("users", "0009_auto_20190119_0941")]

    operations = [
        migrations.AlterField(
            model_name="personalnote",
            name="user",
            field=models.OneToOneField(
                on_delete=openslides.utils.models.CASCADE_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
