# Generated by Django 2.2.12 on 2020-04-06 10:34

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_auth_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vote_weight",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=Decimal("1"), max_digits=15
            ),
        ),
    ]
