# Generated by Django 2.1.5 on 2019-01-18 18:08

import jsonfield.encoder
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0009_auto_20181118_2126")]

    operations = [
        migrations.RemoveField(model_name="projector", name="blank"),
        migrations.RemoveField(model_name="projector", name="config"),
        migrations.AddField(
            model_name="projector",
            name="elements",
            field=jsonfield.fields.JSONField(
                default=list,
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "separators": (",", ":"),
                },
                load_kwargs={},
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projector",
            name="elements_history",
            field=jsonfield.fields.JSONField(
                default=list,
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "separators": (",", ":"),
                },
                load_kwargs={},
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projector",
            name="elements_preview",
            field=jsonfield.fields.JSONField(
                default=list,
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "separators": (",", ":"),
                },
                load_kwargs={},
            ),
            preserve_default=False,
        ),
    ]
