# Generated by Django 2.1.5 on 2019-01-19 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [("core", "0011_auto_20190119_0958")]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=openslides.utils.models.CASCADE_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectiondefault",
            name="projector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projectiondefaults",
                to="core.Projector",
            ),
        ),
    ]
