# Generated by Django 2.1.5 on 2019-01-22 11:16

import jsonfield.encoder
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0014_changed_default_font")]

    operations = [
        migrations.AlterField(
            model_name="projector",
            name="elements",
            field=jsonfield.fields.JSONField(
                default=list,
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "separators": (",", ":"),
                },
                load_kwargs={},
            ),
        ),
        migrations.AlterField(
            model_name="projector",
            name="elements_history",
            field=jsonfield.fields.JSONField(
                default=list,
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "separators": (",", ":"),
                },
                load_kwargs={},
            ),
        ),
        migrations.AlterField(
            model_name="projector",
            name="elements_preview",
            field=jsonfield.fields.JSONField(
                default=list,
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "separators": (",", ":"),
                },
                load_kwargs={},
            ),
        ),
    ]
