# Generated by Django 2.1.5 on 2019-02-27 11:17

from django.db import migrations


def delete_old_countdowns(apps, schema_editor):
    Countdowns = apps.get_model("core", "countdown")
    Countdowns.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [("core", "0018_auto_20190222_1209")]

    operations = [migrations.RunPython(delete_old_countdowns)]
