# Generated by Finn Stutzenstein on 2019-11-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_projector_size_2"),
    ]

    operations = [migrations.RemoveField(model_name="projector", name="height")]
