# Generated by Django 2.2.9 on 2020-03-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_voting_projection_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projector",
            name="width",
            field=models.PositiveIntegerField(default=1200),
        ),
    ]
