# Generated by Django 2.2.4 on 2019-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0011_postgresql_auth_group_id_sequence")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_type",
            field=models.CharField(default="default", max_length=64),
        )
    ]
