# Generated by Django 2.2.12 on 2020-06-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_vote_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": (),
                "ordering": ("last_name", "first_name", "username"),
                "permissions": (
                    ("can_see_name", "Can see names of users"),
                    (
                        "can_see_extra_data",
                        "Can see extra data of users (e.g. email and comment)",
                    ),
                    ("can_change_password", "Can change its own password"),
                    ("can_manage", "Can manage users"),
                ),
            },
        ),
    ]
