# Generated by Django 2.2.16 on 2020-09-03 11:13

from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_rename_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vote_delegated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                related_name="vote_delegated_from_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
