# Generated by Django 2.2.17 on 2021-01-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_vote_delegated_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": (),
                "permissions": (
                    ("can_see_name", "Can see names of users"),
                    (
                        "can_see_extra_data",
                        "Can see extra data of users (e.g. email and comment)",
                    ),
                    ("can_change_password", "Can change its own password"),
                    ("can_manage", "Can manage users"),
                ),
            },
        ),
    ]
