# Generated by Django 2.2.16 on 2020-10-01 19:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_vote_delegated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_weight_2',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_weight_3',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_weight_4',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_weight_5',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
    ]
