# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motions", "0008_auto_20180702_1128")]

    operations = [
        migrations.AddField(
            model_name="motionversion",
            name="modified_final_version",
            field=models.TextField(blank=True, null=True),
        )
    ]
