# Generated by Django 2.1 on 2018-08-31 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """ Cleanup 2 """

    dependencies = [("motions", "0011_motion_version_3")]

    operations = [
        # Cleanup from last migration. Somehow cannot be done there.
        migrations.AlterField(  # remove default=''
            model_name="motion", name="text", field=models.TextField()
        ),
        migrations.AlterField(  # remove default=''
            model_name="motion", name="title", field=models.CharField(max_length=255)
        ),
        migrations.AlterField(  # remove null=True
            model_name="motionchangerecommendation",
            name="motion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_recommendations",
                to="motions.Motion",
            ),
        ),
    ]
