# Generated by Django 2.1 on 2018-08-31 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motions", "0012b_motion_comments_2")]

    operations = [
        # Remove old comment field from motion, use the new model instead
        migrations.RemoveField(model_name="motion", name="comments"),
        migrations.AlterField(
            model_name="motioncomment",
            name="motion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="motions.Motion",
            ),
        ),
    ]
