# Generated by Django 2.1 on 2018-08-31 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import openslides


class Migration(migrations.Migration):

    dependencies = [("users", "0006_user_email"), ("motions", "0011_motion_version_4")]

    operations = [
        # Add extension fields for former "special comments". No hack anymore..
        migrations.AddField(
            model_name="motion",
            name="recommendation_extension",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="motion",
            name="state_extension",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="motion",
            options={
                "default_permissions": (),
                "ordering": ("identifier",),
                "permissions": (
                    ("can_see", "Can see motions"),
                    ("can_create", "Can create motions"),
                    ("can_support", "Can support motions"),
                    ("can_manage", "Can manage motions"),
                ),
                "verbose_name": "Motion",
            },
        ),
        # Comments and CommentsSection models
        migrations.CreateModel(
            name="MotionComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
            ],
            options={"default_permissions": ()},
            bases=(
                openslides.utils.models.RESTModelMixin,  # type: ignore
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MotionCommentSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "read_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_comments",
                        to=settings.AUTH_GROUP_MODEL,
                    ),
                ),
                (
                    "write_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="write_comments",
                        to=settings.AUTH_GROUP_MODEL,
                    ),
                ),
            ],
            options={"default_permissions": ()},
            bases=(
                openslides.utils.models.RESTModelMixin,  # type: ignore
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="motioncomment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="motions.MotionCommentSection",
            ),
        ),
        migrations.AddField(
            model_name="motioncomment",
            name="motion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="motions.Motion"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="motioncomment", unique_together={("motion", "section")}
        ),
    ]
