# Generated by Django 2.1.5 on 2019-01-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motions", "0017_remove_state_action_word")]

    operations = [
        migrations.AlterModelOptions(
            name="motion",
            options={
                "default_permissions": (),
                "ordering": ("identifier",),
                "permissions": (
                    ("can_see", "Can see motions"),
                    ("can_create", "Can create motions"),
                    ("can_create_amendments", "Can create amendments"),
                    ("can_support", "Can support motions"),
                    ("can_manage_metadata", "Can manage motion metadata"),
                    ("can_manage", "Can manage motions"),
                ),
                "verbose_name": "Motion",
            },
        )
    ]
