# Generated by Django 2.1.5 on 2019-01-19 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [("motions", "0019_auto_20190119_1025")]

    operations = [
        migrations.AlterField(
            model_name="motion",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                to="motions.Category",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="motion_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                to="motions.MotionBlock",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                related_name="amendments",
                to="motions.Motion",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="recommendation",
            field=models.ForeignKey(
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                related_name="+",
                to="motions.State",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="sort_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                related_name="children",
                to="motions.Motion",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="statute_paragraph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                related_name="motions",
                to="motions.StatuteParagraph",
            ),
        ),
        migrations.AlterField(
            model_name="motionchangerecommendation",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="motionchangerecommendation",
            name="motion",
            field=models.ForeignKey(
                on_delete=openslides.utils.models.CASCADE_AND_AUTOUPDATE,
                related_name="change_recommendations",
                to="motions.Motion",
            ),
        ),
        migrations.AlterField(
            model_name="motionlog",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="submitter",
            name="user",
            field=models.ForeignKey(
                on_delete=openslides.utils.models.CASCADE_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="first_state",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="motions.State",
            ),
        ),
    ]
