# Generated by Django 2.1.5 on 2019-02-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motions", "0021_state_access_level_2")]

    operations = [
        migrations.RemoveField(model_name="state", name="required_permission_to_see")
    ]
