# Generated by Django 2.1.5 on 2019-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    """ Note: this is a combined migration to execute code in a seperate transaction """

    dependencies = [("motions", "0020_auto_20190119_1425")]

    operations = [
        migrations.AddField(
            model_name="state",
            name="access_level",
            field=models.IntegerField(
                choices=[
                    (0, "All users with permission to see motions"),
                    (
                        1,
                        "Submitters, managers and users with permission to manage metadata",
                    ),
                    (2, "Only managers and users with permission to manage metadata"),
                    (3, "Only managers"),
                ],
                default=0,
            ),
        )
    ]
