# Generated by Django 2.1.7 on 2019-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motions", "0021_state_access_level_3")]

    operations = [
        migrations.AlterModelOptions(
            name="motion",
            options={
                "default_permissions": (),
                "ordering": ("identifier",),
                "permissions": (
                    ("can_see", "Can see motions"),
                    ("can_see_internal", "Can see motions in internal state"),
                    ("can_create", "Can create motions"),
                    ("can_create_amendments", "Can create amendments"),
                    ("can_support", "Can support motions"),
                    ("can_manage_metadata", "Can manage motion metadata"),
                    ("can_manage", "Can manage motions"),
                ),
                "verbose_name": "Motion",
            },
        ),
        migrations.AlterField(
            model_name="state",
            name="access_level",
            field=models.IntegerField(
                choices=[
                    (0, "All users with permission to see motions"),
                    (
                        1,
                        "Submitters, authorized users (with permission to see internal motions), managers and "
                        "users with permission to manage metadata",
                    ),
                    (
                        2,
                        "Only authorized users (with permission to see internal motions), managers and "
                        "users with permission to manage metadata",
                    ),
                    (3, "Only managers"),
                ],
                default=0,
            ),
        ),
    ]
