# Generated by Django 2.1.7 on 2019-03-20 15:49

import jsonfield.encoder
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motions", "0023_remove_motion_log")]

    operations = [
        migrations.AddField(
            model_name="state",
            name="restriction",
            field=jsonfield.fields.JSONField(
                default=list,
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "separators": (",", ":"),
                },
                load_kwargs={},
            ),
        )
    ]
