# Generated by Django 2.2 on 2019-06-03 09:32

from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [("motions", "0027_motion_block_internal")]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"default_permissions": (), "ordering": ["weight"]}
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                related_name="children",
                to="motions.Category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="weight",
            field=models.IntegerField(default=10000),
        ),
    ]
