# Generated by jsangmeister on 2021-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motions", "0037_motionvote_delegated_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="motionvote",
            name="user_token",
            field=models.CharField(null=True, max_length=16),
        ),
    ]
