# Generated by jsangmeister on 2021-03-18 16:27

from django.db import migrations, models

import openslides.poll.models


class Migration(migrations.Migration):

    dependencies = [
        ("motions", "0039_motionvote_user_token_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motionvote",
            name="user_token",
            field=models.CharField(
                null=False,
                default=openslides.poll.models.generate_user_token,
                max_length=16,
            ),
        ),
    ]
