# Generated by jsangmeister on 2021-04-12 13:27

from django.db import migrations

from ...poll.migrations.poll_migration_helper import fix_wrongly_calculated_vote_fields


class Migration(migrations.Migration):

    dependencies = [
        ("motions", "0043_motionpoll_entitled_users_remove_duplicates"),
    ]

    operations = [
        migrations.RunPython(
            fix_wrongly_calculated_vote_fields("motions", "MotionPoll")
        ),
    ]
