bootstrap-admin-username=admin
bootstrap-admin-password=admin
db=postgres
db-debug-jpql=true
db-username=openslides
db-password=openslides
db-url-database=openslides
db-url-host=postgres
db-url-port=5432
db-connect-timeout=10s
