services:
  postgres:
    image: postgres:15
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: openslides
      DATABASE_USER: openslides
      PGPASSWORD: openslides
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
      OPENSLIDES_DEVELOPMENT: 1

  keycloak-server:
    image: quay.io/keycloak/keycloak:26.6.0
    command: start-dev --import-realm
    volumes:
      - ./conf/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./conf/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  keycloak-service:
    build:
        target: "dev"
        args:
            CONTEXT: "dev"
    environment:
        - KEYCLOAK_DATABASE_HOST=postgres
        - KEYCLOAK_DATABASE_PORT=5432
        - KEYCLOAK_DATABASE_NAME=openslides
        - KEYCLOAK_DATABASE_USER=openslides
        - KEYCLOAK_DATABASE_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - ./src:/app/src
    depends_on:
      - keycloak-server
    ports:
      - "8081:8081"
