# Generated by Django 2.1.5 on 2019-01-19 16:41

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mediafiles", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("prefix", models.CharField(blank=True, max_length=32)),
            ],
            options={"ordering": ["prefix"], "default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Motion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("identifier_number", models.IntegerField(null=True)),
                ("origin", models.CharField(blank=True, max_length=255)),
                (
                    "comments",
                    jsonfield.fields.JSONField(
                        dump_kwargs={
                            "cls": jsonfield.encoder.JSONEncoder,
                            "separators": (",", ":"),
                        },
                        load_kwargs={},
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Motion",
                "ordering": ("identifier",),
                "permissions": (
                    ("can_see", "Can see motions"),
                    ("can_create", "Can create motions"),
                    ("can_support", "Can support motions"),
                    ("can_see_comments", "Can see comments"),
                    ("can_manage_comments", "Can manage comments"),
                    ("can_manage", "Can manage motions"),
                ),
                "default_permissions": (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MotionBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MotionChangeRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rejected", models.BooleanField(default=False)),
                ("type", models.PositiveIntegerField(default=0)),
                ("other_description", models.TextField(blank=True)),
                ("line_from", models.PositiveIntegerField()),
                ("line_to", models.PositiveIntegerField()),
                ("text", models.TextField(blank=True)),
                ("creation_time", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MotionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_list",
                    jsonfield.fields.JSONField(
                        dump_kwargs={
                            "cls": jsonfield.encoder.JSONEncoder,
                            "separators": (",", ":"),
                        },
                        load_kwargs={},
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_messages",
                        to="motions.Motion",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-time"], "default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MotionOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MotionPoll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "votesvalid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-2"))
                        ],
                    ),
                ),
                (
                    "votesinvalid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-2"))
                        ],
                    ),
                ),
                (
                    "votescast",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-2"))
                        ],
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="motions.Motion",
                    ),
                ),
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MotionVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                (
                    "amendment_paragraphs",
                    jsonfield.fields.JSONField(
                        dump_kwargs={
                            "cls": jsonfield.encoder.JSONEncoder,
                            "separators": (",", ":"),
                        },
                        load_kwargs={},
                        null=True,
                    ),
                ),
                ("modified_final_version", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("creation_time", models.DateTimeField(auto_now=True)),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="motions.Motion",
                    ),
                ),
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MotionVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-2"))
                        ],
                    ),
                ),
                ("value", models.CharField(max_length=255, null=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="motions.MotionOption",
                    ),
                ),
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("action_word", models.CharField(blank=True, max_length=255)),
                ("recommendation_label", models.CharField(max_length=255, null=True)),
                ("css_class", models.CharField(default="primary", max_length=255)),
                (
                    "required_permission_to_see",
                    models.CharField(blank=True, max_length=255),
                ),
                ("allow_support", models.BooleanField(default=False)),
                ("allow_create_poll", models.BooleanField(default=False)),
                ("allow_submitter_edit", models.BooleanField(default=False)),
                ("versioning", models.BooleanField(default=False)),
                ("leave_old_version_active", models.BooleanField(default=False)),
                ("dont_set_identifier", models.BooleanField(default=False)),
                ("show_state_extension_field", models.BooleanField(default=False)),
                (
                    "show_recommendation_extension_field",
                    models.BooleanField(default=False),
                ),
                ("next_states", models.ManyToManyField(blank=True, to="motions.State")),
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Submitter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(null=True)),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitters",
                        to="motions.Motion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "first_state",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="motions.State",
                    ),
                ),
            ],
            options={"default_permissions": ()},
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="state",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="motions.Workflow",
            ),
        ),
        migrations.AddField(
            model_name="motionoption",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="motions.MotionPoll"
            ),
        ),
        migrations.AddField(
            model_name="motionchangerecommendation",
            name="motion_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_recommendations",
                to="motions.MotionVersion",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="active_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_version",
                to="motions.MotionVersion",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="mediafiles.Mediafile"),
        ),
        migrations.AddField(
            model_name="motion",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="motions.Category",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="motion_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="motions.MotionBlock",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amendments",
                to="motions.Motion",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="recommendation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="motions.State",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="motions.State",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="supporters",
            field=models.ManyToManyField(
                blank=True,
                related_name="motion_supporters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.Tag"),
        ),
        migrations.AlterUniqueTogether(
            name="motionversion", unique_together={("motion", "version_number")}
        ),
    ]
