# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='origin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
