# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 16:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0002_motion_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittersRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'motions_submittersrelationship',
            },
        ),
        migrations.AlterField(
            model_name='motion',
            name='submitters',
            field=models.ManyToManyField(blank=True, related_name='motion_submitters',
                                         through='motions.SubmittersRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submittersrelationship',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motions.Motion'),
        ),
        migrations.AddField(
            model_name='submittersrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='submittersrelationship',
            unique_together=set([('user', 'motion')]),
        ),
    ]
