# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 16:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_submitter_motion_relationship_data(apps, schema_editor):
    """
    Copy all relationship data from motion->ManyToMany->submitters to the model SubmittersRelationship
    """
    Motion = apps.get_model('motions', 'Motion')
    SubmittersRelationship = apps.get_model('motions', 'SubmittersRelationship')
    for motion in Motion.objects.all():
        for index, submitter in enumerate(motion.submitters.all(), start=1):
            SubmittersRelationship.objects.create(
                motion=motion,
                submitter=submitter,
                weight=index)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0004_auto_20160907_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittersRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
            ],
            options={
                'db_table': 'motions_submittersrelationship',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='submittersrelationship',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motions.Motion'),
        ),
        migrations.AddField(
            model_name='submittersrelationship',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='submittersrelationship',
            unique_together=set([('submitter', 'motion'), ('weight', 'motion')]),
        ),
        migrations.RunPython(copy_submitter_motion_relationship_data),
        migrations.RemoveField(
            model_name='motion',
            name='submitters',
        ),
    ]
