# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 21:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0004_auto_20160907_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'default_permissions': (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='motion',
            name='motion_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motions.MotionBlock'),
        ),
    ]
