# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0005_submitters_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='submitters',
        ),
        migrations.AddField(
            model_name='motion',
            name='submitters',
            field=models.ManyToManyField(blank=True, related_name='motion_submitters',
                                         through='motions.SubmittersRelationship', to=settings.AUTH_USER_MODEL),
        ),

    ]
