# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-02 09:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motions", "0007_motionversion_amendment_data")]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="first_state",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="motions.State",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="motions.State",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="next_states",
            field=models.ManyToManyField(blank=True, to="motions.State"),
        ),
        migrations.AlterField(
            model_name="state",
            name="action_word",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
