# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0007_auto_20161027_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionchangerecommendation',
            name='status',
        ),
        migrations.AddField(
            model_name='motionchangerecommendation',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
