# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0008_auto_20161116_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionchangerecommendation',
            name='type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
