# Generated by Django 2.1 on 2018-08-31 13:17

from django.db import migrations


class Migration(migrations.Migration):
    """ Cleanup 1 """

    dependencies = [("motions", "0011_motion_version_2")]

    operations = [
        migrations.RemoveField(
            model_name="motionchangerecommendation", name="motion_version"
        ),
        # remove motion version references from motion and state.
        migrations.RemoveField(model_name="motion", name="active_version"),
        migrations.AlterUniqueTogether(name="motionversion", unique_together=set()),
        migrations.RemoveField(model_name="motionversion", name="motion"),
        migrations.RemoveField(model_name="state", name="leave_old_version_active"),
        migrations.RemoveField(model_name="state", name="versioning"),
        # Delete motion version.
        migrations.DeleteModel(name="MotionVersion"),
    ]
