# Generated by Django 2.1 on 2018-10-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motions", "0013_motion_sorting_and_statute")]

    operations = [
        migrations.AddField(
            model_name="motionchangerecommendation",
            name="internal",
            field=models.BooleanField(default=False),
        )
    ]
