# Generated by Django 2.1.2 on 2018-10-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motions", "0014_motionchangerecommendation_internal")]

    operations = [
        migrations.AlterModelOptions(
            name="motion",
            options={
                "default_permissions": (),
                "ordering": ("identifier",),
                "permissions": (
                    ("can_see", "Can see motions"),
                    ("can_create", "Can create motions"),
                    ("can_support", "Can support motions"),
                    ("can_manage_metadata", "Can manage motion metadata"),
                    ("can_manage", "Can manage motions"),
                ),
                "verbose_name": "Motion",
            },
        )
    ]
