# Generated by Django 2.1.2 on 2018-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motions", "0015_metadata_permission")]

    operations = [
        migrations.AddField(
            model_name="state",
            name="merge_amendment_into_final",
            field=models.SmallIntegerField(default=0),
        )
    ]
