# Generated by Django 2.1.3 on 2018-12-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motions", "0016_merge_amendment_into_final")]

    operations = [migrations.RemoveField(model_name="state", name="action_word")]
