# Generated by Django 2.1.5 on 2019-01-19 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motions", "0018_auto_20190118_2101")]

    operations = [
        migrations.AddField(
            model_name="motion",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motion",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
