# Generated by Django 2.1.7 on 2019-03-20 15:49

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("motions", "0022_auto_20190320_0840")]

    operations = [
        migrations.AddField(
            model_name="state",
            name="restriction",
            field=jsonfield.fields.JSONField(
                default=list,
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "separators": (",", ":"),
                },
                load_kwargs={},
            ),
        )
    ]
