# Generated by Django 2.1.7 on 2019-04-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motions", "0022_auto_20190320_0840")]

    operations = [
        migrations.RemoveField(model_name="motionlog", name="motion"),
        migrations.RemoveField(model_name="motionlog", name="person"),
        migrations.DeleteModel(name="MotionLog"),
    ]
