# Generated by Django 2.1.7 on 2019-03-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motions", "0024_state_restriction_2")]

    operations = [migrations.RemoveField(model_name="state", name="access_level")]
