# Generated by Django 2.2 on 2019-05-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motions", "0026_rename_restriction")]

    operations = [
        migrations.AddField(
            model_name="motionblock",
            name="internal",
            field=models.BooleanField(default=False),
        )
    ]
