#!/bin/bash

set -e

# Set DJANGO_SECRET_KEY variable
source /run/secrets/django || true
[[ -n "$DJANGO_SECRET_KEY" ]] || {
  echo "ERROR: Django secret key undefined!  Cannot continue."
  sleep 5
  exit 2
}
export SECRET_KEY="$DJANGO_SECRET_KEY"

# SAML setup
. /usr/local/lib/saml-setup.sh

wait-for-it -t 0 "${SERVER_SETUP_HOST:-server-setup}:${SERVER_SETUP_PORT:-8000}"

printf 'Executing server: "%s"\n' "$*"

# Expected commands are one of:
# - daphne -b 0.0.0.0 -p 8000 openslides.asgi:application
# - gunicorn -w 4 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker \
#   openslides.asgi:application
exec "$@"
