# Start with the Keycloak image
FROM quay.io/keycloak/keycloak:latest

# Install dependencies for Argon2
USER root
RUN apt-get update && \
    apt-get install -y libargon2-1-dev && \
    rm -rf /var/lib/apt/lists/*

USER keycloak
