# Generated by Finn Stutzenstein on 2021-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("users", "0016_remove_user_ordering"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatgroup",
            old_name="access_groups",
            new_name="read_groups",
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="read_groups",
            field=models.ManyToManyField(
                blank=True, related_name="chat_read_groups", to="users.Group"
            ),
        ),
        migrations.AddField(
            model_name="chatgroup",
            name="write_groups",
            field=models.ManyToManyField(
                blank=True, related_name="chat_write_groups", to="users.Group"
            ),
        ),
    ]
