# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
