# Generated by Django 2.1.5 on 2019-01-19 13:25

from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [("mediafiles", "0002_mediafile_private")]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=openslides.utils.models.SET_NULL_AND_AUTOUPDATE,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
