# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_mediafile_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={
                    'default_permissions': (),
                    'ordering': ['title'],
                    'permissions': (
                                    ('can_see', 'Can see the list of files'),
                                    ('can_see_private', 'Can see private files'),
                                    ('can_upload', 'Can upload files'),
                                    ('can_manage', 'Can manage files'))},
        ),
    ]
