# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_auto_20160514_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={
                    'default_permissions': (),
                    'ordering': ['title'],
                    'permissions': (
                        ('can_see', 'Can see the list of files'),
                        ('can_see_hidden', 'Can see hidden files'),
                        ('can_upload', 'Can upload files'),
                        ('can_manage', 'Can manage files'))},
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='private',
            new_name='hidden',
        ),
    ]
