# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("assignments", "0002_assignmentpoll_pollmethod")]

    operations = [
        migrations.AddField(
            model_name="assignmentrelateduser",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assignmentoption",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
