# Generated by Django 2.2.12 on 2020-04-06 11:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0011_voting_4"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assignmentvote", unique_together={("user", "option")}
        ),
    ]
