# Generated by Django 2.2.9 on 2020-05-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0012_assignment_vote_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentpoll",
            name="type",
            field=models.CharField(
                choices=[
                    ("analog", "analog"),
                    ("named", "nominal"),
                    ("pseudoanonymous", "non-nominal"),
                ],
                max_length=64,
            ),
        ),
    ]
