# Generated by Django 2.2.16 on 2020-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_assignmentvote_delegated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpoll',
            name='voting_principle',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
