# Generated by Django 2.2.15 on 2020-11-24 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0017_vote_to_y"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignmentpoll",
            old_name="votes_amount",
            new_name="max_votes_amount",
        ),
        migrations.AddField(
            model_name="assignmentpoll",
            name="min_votes_amount",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
