# Generated by jsangmeister on 2021-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0018_votes_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentvote",
            name="user_token",
            field=models.CharField(null=True, max_length=16),
        ),
    ]
