# Generated by jsangmeister on 2021-03-25 10:41

from django.db import migrations

from ...poll.migrations.vote_migration_helper import set_user_tokens


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0019_assignmentvote_user_token_1"),
    ]

    operations = [
        migrations.RunPython(set_user_tokens("assignments", "AssignmentVote")),
    ]
