# Generated by jsangmeister on 2021-03-25 10:41

from django.db import migrations, models

import openslides.poll.models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0020_assignmentvote_user_token_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentvote",
            name="user_token",
            field=models.CharField(
                null=False,
                default=openslides.poll.models.generate_user_token,
                max_length=16,
            ),
        ),
    ]
