# Generated by jsangmeister on 2021-03-22 12:44

from django.db import migrations

from ...poll.migrations.poll_migration_helper import (
    calculate_vote_fields,
    set_is_pseudoanonymized,
)


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0022_assignmentpoll_change_fields_1"),
    ]

    operations = [
        migrations.RunPython(set_is_pseudoanonymized("assignments", "AssignmentPoll")),
        migrations.RunPython(calculate_vote_fields("assignments", "AssignmentPoll")),
    ]
