# Generated by jsangmeister on 2021-04-08 11:27

from django.db import migrations

from ...poll.migrations.poll_migration_helper import remove_entitled_users_duplicates


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0023_assignmentpoll_change_fields_2"),
    ]

    operations = [
        migrations.RunPython(
            remove_entitled_users_duplicates("assignments", "AssignmentPoll")
        ),
    ]
