# Generated by jsangmeister on 2021-04-15 08:01

from django.db import migrations

from ...poll.migrations.poll_migration_helper import fix_wrongly_calculated_vote_fields


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0024_assignmentpoll_entitled_users_remove_duplicates"),
    ]

    operations = [
        migrations.RunPython(
            fix_wrongly_calculated_vote_fields(
                "assignments",
                "AssignmentPoll",
                lambda poll: not poll.is_pseudoanonymized,
            )
        ),
    ]
