# Generated by Django 2.2.13 on 2020-06-26 12:17

from django.db import migrations, models

import openslides.utils.models


def add_poster_projection_default(apps, schema_editor):
    """
    Adds the projectiondefault for posters.
    """
    Projector = apps.get_model("core", "Projector")
    ProjectionDefault = apps.get_model("core", "ProjectionDefault")
    default_projector = Projector.objects.order_by("pk").first()

    projection_default = ProjectionDefault(
        name="posters", display_name="Posters", projector=default_projector,
    )
    projection_default.save(skip_autoupdate=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = [("core", "0002_misc_features")]

    operations = [
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("xml", models.TextField(blank=True)),
                ("published", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "verbose_name": "Poster",
                "permissions": (
                    ("can_see", "Can see posters"),
                    ("can_manage", "Can manage posters"),
                ),
                "default_permissions": (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.RunPython(add_poster_projection_default),
    ]
