# Generated by Django 2.1.5 on 2019-01-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import openslides.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True, null=True)),
                ("closed", models.BooleanField(default=False)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Agenda item"),
                            (2, "Internal item"),
                            (3, "Hidden item"),
                        ],
                        default=3,
                    ),
                ),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(default=10000)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("speaker_list_closed", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="agenda.Item",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("can_see", "Can see agenda"),
                    ("can_manage", "Can manage agenda"),
                    ("can_manage_list_of_speakers", "Can manage list of speakers"),
                    (
                        "can_see_internal_items",
                        "Can see internal items and time scheduling of agenda",
                    ),
                ),
                "default_permissions": (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begin_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("weight", models.IntegerField(null=True)),
                ("marked", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="agenda.Item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("can_be_speaker", "Can put oneself on the list of speakers"),
                ),
                "default_permissions": (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name="item", unique_together={("content_type", "object_id")}
        ),
    ]
