# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("agenda", "0003_auto_20170818_1202")]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="marked",
            field=models.BooleanField(default=False),
        )
    ]
