# Generated by Django 2.1.7 on 2019-04-25 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("agenda", "0007_list_of_speakers_2")]

    operations = [
        migrations.RemoveField(model_name="item", name="speaker_list_closed"),
        migrations.AlterField(
            model_name="speaker",
            name="list_of_speakers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers",
                to="agenda.ListOfSpeakers",
            ),
        ),
        migrations.RemoveField(model_name="speaker", name="item"),
    ]
