# Generated by Django 2.2.12 on 2020-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_projector_default_height"),
        ("agenda", "0008_default_ordering_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.Tag"),
        ),
    ]
