name: Make github release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: "${{ inputs.branch }}"

      - name: Set release date
        run: |
          echo "RELEASE_DATE=$(date -I)" >> $GITHUB_ENV

      - name: Set release body
        run: |
          RELEASE_BODY=$(
            cat patchnotes/${{ github.ref_name }}.md
            echo ""
            echo "For instructions on how to use production ready docker images, see [INSTALL.md](https://github.com/OpenSlides/OpenSlides/blob/main/INSTALL.md)"
          )
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: "OpenSlides version ${{ github.ref_name }} ($RELEASE_DATE)"
          body: "$RELEASE_BODY"

